app:
  name: ${APP_NAME:Transaction Service}
  version: ${APP_VERSION:1.0}
  description: ${APP_DESCRIPTION:Example Microservice}
  baseUrl: ${APP_BASE_URL:http://localhost:8080}
  mongo:
    uri: ${APP_MONGO_URI:mongodb://localhost:27017}
    database: ${APP_MONGO_DB:radar}
  exampleBaseUrl: ${EXAMPLE_BASE_URL:https://run.mocky.io}
server:
  port: ${SERVER_PORT:8080}
